# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: livermetabolism.com
email: konigmatt@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Projects of the LiSyM Junior Group König.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.livermetabolism.com" # the base hostname & protocol for your site
twitter_username: konigmatt
github_username:  matthiaskoenig

# Build settings
markdown: kramdown
