1. #fa-icon("database") #link("https://github.com/matthiaskoenig/pkdb")[#fa-icon("git-alt")] Database *PK-DB - Pharmacokinetics database*. #link("https://doi.org/10.1093/nar/gkaa990")[doi:10.1093/nar/gkaa990] An open database for pharmacokinetics information from clinical trials as well as pre-clinical research.
2. #fa-icon("gear") #link("https://github.com/matthiaskoenig/sbmlutils")[#fa-icon("git-alt")] Software *sbmlutils - Python utilities for SBML*. #link("https://doi.org/10.5281/zenodo.597149")[doi:10.5281/zenodo.597149] sbmlutils is a collection of python utilities for working with SBML models implemented on top of libsbml and other libraries.
3. #fa-icon("gear") #link("https://github.com/matthiaskoenig/sbmlutils")[#fa-icon("git-alt")] Software *SBML4Humans - SBML simulation made easy*.  The objective of SBML4Humans is to provide an interactive and reactive report for SBML models which allows humans (experts as well as beginners) to easily comprehend the content of a model.
4. #fa-icon("gear") #link("https://github.com/matthiaskoenig/sbmlsim")[#fa-icon("git-alt")] Software *sbmlsim - SBML simulation made easy*.  sbmlsim is a collection of python utilities to simplify simulations with SBML models implemented on top of roadrunner.
5. #fa-icon("gear") #link("https://github.com/matthiaskoenig/cy3sbml")[#fa-icon("git-alt")] Software *cysbml - Cytoscape 3 app for the Systems Biology Markup Language*. #link("https://doi.org/10.5281/zenodo.597154")[doi:10.5281/zenodo.597154] cy3sbml is a Cytoscape 3 app for the Systems Biology Markup Language SBML. Our mission is the visualization of SBML information within the network context.
6. #fa-icon("gear") #link("https://github.com/matthiaskoenig/brendapy")[#fa-icon("git-alt")] Software *brendapy - BRENDA in python*.  The brendapy package provides a python parser and utility functions for enzyme information from BRENDA.
7. #fa-icon("gear") #link("https://github.com/matthiaskoenig/libsbgn-python")[#fa-icon("git-alt")] Software *libsbgnpy - Python library for SBGN*.  Python library to work with the Systems Biology Graphical Notation (SBGN).
8. #fa-icon("gear") #link("https://github.com/sys-bio/roadrunner/")[#fa-icon("git-alt")] Software *roadrunner - High-performance simulator for SBML*.  libRoadRunner is a C/C++ library that supports simulation of SBML based models. It uses LLVM) to generate extremely high performance code.
9. #fa-icon("gear") #link("https://github.com/opencobra/cobrapy/")[#fa-icon("git-alt")] Software *COBRApy - COBRA python package*.  COBRApy is a constraint-based modeling package that is designed to accommodate the biological complexity of the next generation of COBRA models and provides access to commonly used COBRA methods, such as flux balance analysis, flux variability analysis, and gene deletion analyses.
10. #fa-icon("gear") #link("https://github.com/sys-bio/tellurium/")[#fa-icon("git-alt")] Software *cobrapy - tellurium simulator*.  Tellurium is a python environment for reproducible dynamical modeling of biological networks. Tellurium provides the interfacial code to convert between standard formats and utilize powerful libraries without requiring technical expertise, allowing you to focus on what’s important: building better models.
